apiVersion: v1
kind: ConfigMap
metadata:
  name: block-mechanica-config
  namespace: rbd-system
data:
  HOST: "0.0.0.0"
  PORT: "8080"
  SERVICE_NAME: "block-mechanica"
  READINESS_PATH: "/readyz"
  LIVENESS_PATH: "/livez"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: block-mechanica-sa
  namespace: rbd-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: block-mechanica-role
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["apps.kubeblocks.io"]
    resources: ["clusters"]
    verbs: ["get", "list", "watch", "create", "patch", "delete"]
  - apiGroups: ["operations.kubeblocks.io"]
    resources: ["opsrequests"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["dataprotection.kubeblocks.io"]
    resources: ["backuprepos"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["dataprotection.kubeblocks.io"]
    resources: ["backups"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: block-mechanica-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: block-mechanica-role
subjects:
  - kind: ServiceAccount
    name: block-mechanica-sa
    namespace: rbd-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: block-mechanica
  namespace: rbd-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: block-mechanica
  template:
    metadata:
      labels:
        app: block-mechanica
    spec:
      serviceAccountName: block-mechanica-sa
      containers:
        - name: block-mechanica
          image: 10.135.115.1:5000/block-mechanica:0.9.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: block-mechanica-config
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: block-mechanica
  namespace: rbd-system
spec:
  selector:
    app: block-mechanica
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
